### ISSUE TITLE
Canada case failing

### ISSUE THREAD

**Issue by vgoliber** [dwave-examples/graph-coloring#14]
Error message:

Reading shp file...
Traceback (most recent call last):
  File "/workspace/graph-coloring/map_coloring.py", line 157, in <module>
    state_records, state_neighbors = get_state_info(input_shp_file)
  File "/workspace/graph-coloring/map_coloring.py", line 49, in get_state_info
    for state in sf.records():
  File "/workspace/.pip-modules/lib/python3.7/site-packages/shapefile.py", line 1306, in records
    r = self.__record(oid=i)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/shapefile.py", line 1281, in __record
    value = u(value, self.encoding, self.encodingErrors)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/shapefile.py", line 104, in u
    return v.decode(encoding, encodingErrors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 11: invalid continuation byte

**Comment by vgoliber** [comment]
Should also add smoke test to Canada case for unit tests
